import { User, UserRole, Course, StudentProgress, ChatMessage, LiveSession, OneToOneSession, Banner, CourseDifficulty, Quiz } from './types';

// USERS
export const USERS: User[] = [
    { id: 'user-1', name: 'Alice Johnson', email: 'alice@example.com', role: UserRole.Student },
    { id: 'user-2', name: 'Bob Williams', email: 'bob@example.com', role: UserRole.Student },
    { id: 'user-3', name: 'Charlie Brown', email: 'charlie@example.com', role: UserRole.Instructor },
    { id: 'user-4', name: 'Diana Prince', email: 'diana@example.com', role: UserRole.Admin },
    { id: 'user-5', name: 'Ethan Hunt', email: 'ethan@example.com', role: UserRole.Instructor },
    { id: 'user-6', name: 'Fiona Gallagher', email: 'fiona@example.com', role: UserRole.Student },
    { id: 'user-7', name: 'George Costanza', email: 'george@example.com', role: UserRole.Student },
    { id: 'user-8', name: 'Hannah Montana', email: 'hannah@example.com', role: UserRole.Student },
    { id: 'user-9', name: 'Ian Malcolm', email: 'ian@example.com', role: UserRole.Student },
    { id: 'user-10', name: 'Jane Doe', email: 'jane@example.com', role: UserRole.Student },
    { id: 'user-11', name: 'Kevin McCallister', email: 'kevin@example.com', role: UserRole.Student },
    { id: 'user-12', name: 'Lara Croft', email: 'lara@example.com', role: UserRole.Student },
    { id: 'user-13', name: 'Michael Scott', email: 'michael@example.com', role: UserRole.Instructor },
    { id: 'user-14', name: 'Nancy Drew', email: 'nancy@example.com', role: UserRole.Instructor },
    { id: 'user-15', name: 'Oscar Martinez', email: 'oscar@example.com', role: UserRole.Instructor },
    { id: 'user-16', name: 'Peter Parker', email: 'peter@example.com', role: UserRole.Student },
    { id: 'user-17', name: 'Quentin Beck', email: 'quentin@example.com', role: UserRole.Instructor },
    { id: 'user-18', name: 'Rachel Green', email: 'rachel@example.com', role: UserRole.Student },
    { id: 'user-19', name: 'Steve Rogers', email: 'steve@example.com', role: UserRole.Student },
    { id: 'user-20', name: 'Tony Stark', email: 'tony@example.com', role: UserRole.Instructor },
    { id: 'user-21', name: 'Ursula Buffay', email: 'ursula@example.com', role: UserRole.Student },
    { id: 'user-22', name: 'Victor Von Doom', email: 'victor@example.com', role: UserRole.Instructor },
    { id: 'user-23', name: 'Wanda Maximoff', email: 'wanda@example.com', role: UserRole.Student },
    { id: 'user-24', name: 'Xavier Charles', email: 'xavier@example.com', role: UserRole.Student },
    { id: 'user-25', name: 'Yelena Belova', email: 'yelena@example.com', role: UserRole.Student },
];

// QUIZZES
export const QUIZZES: Quiz[] = [
    { id: 'q1', title: 'Fundamentals Quiz', questions: [{ text: 'What does "bull market" mean?', options: ['Prices are falling', 'Prices are rising', 'Prices are stable'], correctAnswerIndex: 1 }, { text: 'What is a dividend?', options: ['A company expense', 'A loan to the company', 'A distribution of profits to shareholders'], correctAnswerIndex: 2 }] },
    { id: 'q2', title: 'Options Strategy Quiz', questions: [{ text: 'An Iron Condor is a...', options: ['Bullish strategy', 'Bearish strategy', 'Neutral strategy'], correctAnswerIndex: 2 }] },
    { id: 'q3', title: 'Beginner Concepts Quiz', questions: [{ text: 'What does owning a stock mean?', options: ["You own the company's debt", "You own a piece of the company", "You are the company's creditor"], correctAnswerIndex: 1 }] },
    { id: 'q4', title: 'Fund Fundamentals Quiz', questions: [{ text: 'Which fund type trades on an exchange throughout the day like a stock?', options: ["Mutual Fund", "ETF", "Both"], correctAnswerIndex: 1 }] },
    { id: 'q5', title: 'Financial Statements Quiz', questions: [{ text: 'Which statement shows a company\'s financial position at a single point in time?', options: ["Income Statement", "Balance Sheet", "Cash Flow Statement"], correctAnswerIndex: 1 }] },
    { id: 'q6', title: 'Chart Patterns Quiz', questions: [{ text: 'A "Head and Shoulders" pattern is typically a...', options: ["Continuation pattern", "Bearish reversal pattern", "Bullish reversal pattern"], correctAnswerIndex: 1 }] },
    { id: 'q7', title: 'Analysis Quiz', questions: [{ text: 'What is the primary goal of fundamental analysis?', options: ["To predict short-term price swings", "To determine a company's long-term intrinsic value", "To follow market trends"], correctAnswerIndex: 1 }] },
    { id: 'q8', title: 'Value Investing Quiz', questions: [{ text: 'Value investors look for stocks that are...', options: ["Trading above their intrinsic value", "Trading below their intrinsic value", "Trending upwards"], correctAnswerIndex: 1 }] },
    { id: 'q9', title: 'Growth Investing Quiz', questions: [{ text: 'Growth investors are primarily focused on a company\'s...', options: ["Current profitability", "Future potential and revenue growth", "Dividend payments"], correctAnswerIndex: 1 }] },
    { id: 'q10', title: 'Dividend Quiz', questions: [{ text: 'What is a DRIP?', options: ["A falling stock price", "A type of stock option", "Dividend Reinvestment Plan"], correctAnswerIndex: 2 }] },
    { id: 'q11', title: 'Swing Trading Quiz', questions: [{ text: 'A typical swing trade lasts for...', options: ["A few seconds", "A few days to weeks", "Several years"], correctAnswerIndex: 1 }] },
    { id: 'q12', title: 'Day Trading Quiz', questions: [{ text: 'What is a key requirement for day trading?', options: ["A long-term perspective", "High-speed internet and direct access brokerage", "Ignoring market news"], correctAnswerIndex: 1 }] },
    { id: 'q13', title: 'Risk Management Quiz', questions: [{ text: 'A stop-loss order is designed to...', options: ["Guarantee a profit", "Limit your potential loss on a trade", "Buy more shares automatically"], correctAnswerIndex: 1 }] },
    { id: 'q14', title: 'Trading Psychology Quiz', questions: [{ text: 'FOMO often leads to...', options: ["Careful analysis", "Chasing trades and overpaying", "Taking profits too early"], correctAnswerIndex: 1 }] },
    { id: 'q15', title: 'IPO Quiz', questions: [{ text: 'An IPO is when a company...', options: ["Is bought by another company", "Sells shares to the public for the first time", "Declares bankruptcy"], correctAnswerIndex: 1 }] },
    { id: 'q16', title: 'REITs Quiz', questions: [{ text: 'REITs are legally required to pay out at least what percentage of their taxable income to shareholders?', options: ["50%", "75%", "90%"], correctAnswerIndex: 2 }] },
    { id: 'q17', title: 'Forex Quiz', questions: [{ text: 'In the EUR/USD pair, which is the "base" currency?', options: ["EUR", "USD"], correctAnswerIndex: 0 }] },
    { id: 'q18', title: 'Crypto Quiz', questions: [{ text: 'What is the term for all cryptocurrencies other than Bitcoin?', options: ["Sidecoins", "Altcoins", "Othercoins"], correctAnswerIndex: 1 }] },
    { id: 'q19', title: 'Portfolio Quiz', questions: [{ text: 'Diversification helps to reduce which type of risk?', options: ["Systematic risk", "Unsystematic risk", "All risk"], correctAnswerIndex: 1 }] },
    { id: 'q20', title: 'Retirement Quiz', questions: [{ text: 'Which IRA type is funded with post-tax dollars, allowing for tax-free withdrawals in retirement?', options: ["Traditional IRA", "Roth IRA"], correctAnswerIndex: 1 }] },
    { id: 'q21', title: 'Economics Quiz', questions: [{ text: 'A high CPI reading generally indicates...', options: ["Deflation", "Economic recession", "Inflation"], correctAnswerIndex: 2 }] },
    { id: 'q22', title: 'Sector Quiz', questions: [{ text: 'During a recession, which sector is considered "defensive"?', options: ["Technology", "Consumer Staples", "Financials"], correctAnswerIndex: 1 }] },
    { id: 'q23', title: 'Blue-Chip Quiz', questions: [{ text: 'Blue-chip stocks are generally known for their...', options: ["High volatility", "Reliability and stable earnings", "Fast growth"], correctAnswerIndex: 1 }] },
    { id: 'q24', title: 'Candlestick Quiz', questions: [{ text: 'A "Doji" candlestick suggests...', options: ["A strong trend", "Indecision in the market", "A guaranteed reversal"], correctAnswerIndex: 1 }] },
    { id: 'q25', title: 'Advanced TA Quiz', questions: [{ text: 'The key Fibonacci retracement levels are typically 38.2%, 50%, and...', options: ["55.5%", "61.8%", "75.1%"], correctAnswerIndex: 1 }] },
    { id: 'q26', title: 'Bonds Quiz', questions: [{ text: 'When interest rates rise, what happens to the price of existing bonds?', options: ["It rises", "It falls", "It stays the same"], correctAnswerIndex: 1 }] },
    { id: 'q27', title: 'ESG Quiz', questions: [{ text: 'Which of these is a "Social" factor in ESG?', options: ["Carbon emissions", "Employee relations", "Board diversity"], correctAnswerIndex: 1 }] },
    { id: 'q28', title: 'Behavioral Finance Quiz', questions: [{ text: 'Selling winning stocks too early and holding losing stocks too long is an example of the...', options: ["Confirmation Bias", "Disposition Effect", "Anchoring Bias"], correctAnswerIndex: 1 }] },
    { id: 'q29', title: 'Indicators Quiz', questions: [{ text: 'An RSI reading above 70 typically suggests a stock is...', options: ["Oversold", "Overbought", "Fairly valued"], correctAnswerIndex: 1 }] },
    { id: 'q30', title: 'Tax Investing Quiz', questions: [{ text: 'Long-term capital gains are typically taxed at a ... rate than short-term gains.', options: ["higher", "lower", "similar"], correctAnswerIndex: 1 }] },
    { id: 'q31', title: 'Greeks Quiz', questions: [{ text: 'Which Greek measures the rate of time decay?', options: ["Delta", "Vega", "Theta"], correctAnswerIndex: 2 }] },
    { id: 'q32', title: 'Short Selling Quiz', questions: [{ text: 'What is the maximum potential loss on a short sale?', options: ["The initial investment", "Double the investment", "Unlimited"], correctAnswerIndex: 2 }] },
    { id: 'q33', title: 'Financial Planning Quiz', questions: [{ text: 'The biggest advantage young investors have is...', options: ["Experience", "Time and compounding", "A high risk tolerance"], correctAnswerIndex: 1 }] },
    { id: 'q34', title: 'Tech Stocks Quiz', questions: [{ text: 'What does "SaaS" stand for?', options: ["Software as a Subscription", "Software as a Service", "Sales as a Service"], correctAnswerIndex: 1 }] },
    { id: 'q35', title: 'Algo Trading Quiz', questions: [{ text: 'What is backtesting?', options: ["Testing a strategy on future data", "Testing a strategy on historical data", "Running a strategy in real-time"], correctAnswerIndex: 1 }] },
    { id: 'q36', title: 'Futures Quiz', questions: [{ text: 'Futures contracts are...', options: ["Standardized agreements to buy/sell at a future date", "Flexible agreements between two parties", "The same as options"], correctAnswerIndex: 0 }] },
    { id: 'q37', title: 'Roth IRA Quiz', questions: [{ text: 'At what age can you typically withdraw Roth IRA earnings tax-free and penalty-free?', options: ["55", "59 1/2", "65"], correctAnswerIndex: 1 }] },
    { id: 'q38', title: 'Margin Quiz', questions: [{ text: 'Using leverage...', options: ["Reduces risk", "Magnifies both gains and losses", "Guarantees higher returns"], correctAnswerIndex: 1 }] },
    { id: 'q39', title: 'Small-Cap Quiz', questions: [{ text: 'Compared to large-cap stocks, small-cap stocks are generally...', options: ["Less volatile", "More volatile", "Equally volatile"], correctAnswerIndex: 1 }] },
    { id: 'q40', title: 'Global Investing Quiz', questions: [{ text: 'Which is an example of an emerging market?', options: ["Japan", "Germany", "Brazil"], correctAnswerIndex: 2 }] },
    { id: 'q41', title: 'Modeling Quiz', questions: [{ text: 'A DCF model estimates a company\'s value based on its...', options: ["Past earnings", "Book value", "Future cash flows"], correctAnswerIndex: 2 }] },
    { id: 'q42', title: 'Hedge Fund Quiz', questions: [{ text: 'Hedge funds aim to generate...', options: ["Relative returns", "Absolute returns", "Guaranteed returns"], correctAnswerIndex: 1 }] },
    { id: 'q43', title: 'Lynch Quiz', questions: [{ text: 'Peter Lynch is famous for managing which fund?', options: ["Vanguard 500", "Berkshire Hathaway", "Fidelity Magellan Fund"], correctAnswerIndex: 2 }] },
    { id: 'q44', title: 'Healthcare Investing Quiz', questions: [{ text: 'A "patent cliff" refers to...', options: ["A new drug discovery", "The expiration of a drug\'s patent protection", "A failed clinical trial"], correctAnswerIndex: 1 }] },
    { id: 'q45', title: 'Penny Stocks Quiz', questions: [{ text: 'Penny stocks are known for their...', options: ["Low risk and high liquidity", "High risk and low liquidity", "Stable dividends"], correctAnswerIndex: 1 }] },
    { id: 'q46', title: 'Advanced TA Quiz', questions: [{ text: 'In Volume Profile, the POC (Point of Control) represents...', options: ["The highest price traded", "The price level with the most volume", "The opening price"], correctAnswerIndex: 1 }] },
    { id: 'q47', title: 'Long-Term Quiz', questions: [{ text: 'Dollar-cost averaging involves investing...', options: ["A large lump sum at once", "Fixed amounts at regular intervals", "Only when the market is rising"], correctAnswerIndex: 1 }] },
    { id: 'q48', title: 'Hedging Quiz', questions: [{ text: 'To hedge a portfolio of stocks against a drop in price, you would...', options: ["Buy call options", "Sell call options", "Buy put options"], correctAnswerIndex: 2 }] },
    { id: 'q49', title: 'ETN Quiz', questions: [{ text: 'The primary risk unique to ETNs compared to ETFs is...', options: ["Market risk", "Credit risk of the issuer", "Interest rate risk"], correctAnswerIndex: 1 }] },
    { id: 'q50', title: 'Market Structure Quiz', questions: [{ text: 'A market maker provides liquidity by simultaneously quoting...', options: ["A buy price only", "A sell price only", "Both a buy (bid) and sell (ask) price"], correctAnswerIndex: 2 }] }
];


// COURSES
export const COURSES: Course[] = [
    {
        id: 'course-1',
        title: 'Introduction to Stock Trading',
        description: 'Learn the fundamentals of stock trading, from market analysis to risk management.',
        instructorId: 'user-3',
        thumbnailUrl: 'https://placehold.co/400x225/4f46e5/ffffff/png?font=lato&text=Introduction+to+Stock+Trading',
        rating: 4.5,
        totalRatings: 120,
        price: 7999,
        category: 'Trading Fundamentals',
        difficulty: CourseDifficulty.Beginner,
        modules: [
            { id: 'm1-1', title: 'What is the Stock Market?', type: 'text', content: 'The stock market refers to the collection of markets and exchanges where regular activities of buying, selling, and issuance of shares of publicly-held companies take place.', durationMinutes: 15 },
            { id: 'm1-2', title: 'Reading Stock Charts', type: 'video', content: 'https://archive.org/download/BigBuckBunny_328/BigBuckBunny_512kb.mp4', durationMinutes: 10 },
        ],
        quizId: 'q1',
    },
    {
        id: 'course-2',
        title: 'Advanced Options Trading',
        description: 'Master complex options strategies to maximize your returns and hedge your positions.',
        instructorId: 'user-5',
        thumbnailUrl: 'https://placehold.co/400x225/4f46e5/ffffff/png?font=lato&text=Advanced+Options+Trading',
        rating: 4.8,
        totalRatings: 85,
        price: 19999,
        category: 'Advanced Strategies',
        difficulty: CourseDifficulty.Advanced,
        modules: [
            { id: 'm2-1', title: 'Understanding Calls and Puts', type: 'text', content: 'A call option gives the holder the right to buy a stock and a put option gives the holder the right to sell a stock.', durationMinutes: 20 },
            { id: 'm2-2', title: 'The Iron Condor Strategy', type: 'video', content: 'https://www.youtube.com/embed/JAr2rUbgGJE', durationMinutes: 40 },
        ],
        quizId: 'q2',
    },
    {
        id: 'course-3',
        title: 'Stock Market for Absolute Beginners',
        description: 'Your first step into the world of investing. This course demystifies the stock market, explaining basic concepts in simple, easy-to-understand language.',
        instructorId: 'user-3',
        thumbnailUrl: 'https://placehold.co/400x225/4f46e5/ffffff/png?font=lato&text=Stock+Market+for+Absolute+Beginners',
        rating: 4.7,
        totalRatings: 350,
        price: 3999,
        category: 'Investment Basics',
        difficulty: CourseDifficulty.Beginner,
        modules: [
            { id: 'm3-1', title: 'What is a Stock?', type: 'text', content: 'Learn what a stock represents, why companies issue them, and the rights of a shareholder.', durationMinutes: 10 },
            { id: 'm3-2', title: 'How the Stock Market Works', type: 'video', content: 'https://archive.org/download/BigBuckBunny_328/BigBuckBunny_512kb.mp4', durationMinutes: 15 },
            { id: 'm3-3', title: 'Opening a Brokerage Account', type: 'text', content: 'A step-by-step guide to choosing the right broker and opening your first investment account.', durationMinutes: 20 },
        ],
        quizId: 'q3',
    },
    {
        id: 'course-4',
        title: 'Understanding ETFs and Mutual Funds',
        description: 'Learn the difference between ETFs and mutual funds, how they work, and how to use them to build a diversified portfolio with ease.',
        instructorId: 'user-5',
        thumbnailUrl: 'https://placehold.co/400x225/4f46e5/ffffff/png?font=lato&text=Understanding+ETFs+and+Mutual+Funds',
        rating: 4.6,
        totalRatings: 210,
        price: 6399,
        category: 'Portfolio Management',
        difficulty: CourseDifficulty.Beginner,
        modules: [
            { id: 'm4-1', title: 'ETFs vs. Mutual Funds', type: 'text', content: 'A detailed comparison of the two most popular investment vehicles.', durationMinutes: 20 },
            { id: 'm4-2', title: 'Index Fund Investing', type: 'video', content: 'https://archive.org/download/BigBuckBunny_328/BigBuckBunny_512kb.mp4', durationMinutes: 25 },
        ],
        quizId: 'q4',
    },
    {
        id: 'course-5',
        title: 'How to Read Financial Statements',
        description: 'Unlock the secrets hidden in balance sheets, income statements, and cash flow statements to make smarter investment decisions.',
        instructorId: 'user-3',
        thumbnailUrl: 'https://placehold.co/400x225/4f46e5/ffffff/png?font=lato&text=How+to+Read+Financial+Statements',
        rating: 4.9,
        totalRatings: 180,
        price: 11999,
        category: 'Financial Analysis',
        difficulty: CourseDifficulty.Intermediate,
        modules: [
            { id: 'm5-1', title: 'The Income Statement', type: 'text', content: 'Understand revenue, expenses, and profit.', durationMinutes: 25 },
            { id: 'm5-2', title: 'The Balance Sheet', type: 'text', content: 'Analyze assets, liabilities, and equity.', durationMinutes: 25 },
        ],
        quizId: 'q5',
    },
    {
        id: 'course-6',
        title: 'Technical Analysis: Chart Patterns',
        description: 'Learn to identify key chart patterns like Head and Shoulders, Triangles, and Flags to predict future price movements.',
        instructorId: 'user-5',
        thumbnailUrl: 'https://placehold.co/400x225/4f46e5/ffffff/png?font=lato&text=Technical+Analysis:+Chart+Patterns',
        rating: 4.4,
        totalRatings: 280,
        price: 15999,
        category: 'Technical Analysis',
        difficulty: CourseDifficulty.Intermediate,
        modules: [
            { id: 'm6-1', title: 'Introduction to Candlesticks', type: 'video', content: 'https://archive.org/download/BigBuckBunny_328/BigBuckBunny_512kb.mp4', durationMinutes: 30 },
            { id: 'm6-2', title: 'Recognizing Reversal Patterns', type: 'text', content: 'Spotting trends that are about to change direction.', durationMinutes: 45 },
        ],
        quizId: 'q6',
    },
    {
        id: 'course-7',
        title: 'Fundamental Analysis Deep Dive',
        description: 'Go beyond the basics to evaluate a company\'s intrinsic value by analyzing economic factors, management, and financial health.',
        instructorId: 'user-3',
        thumbnailUrl: 'https://placehold.co/400x225/4f46e5/ffffff/png?font=lato&text=Fundamental+Analysis+Deep+Dive',
        rating: 4.8,
        totalRatings: 155,
        price: 23999,
        category: 'Financial Analysis',
        difficulty: CourseDifficulty.Advanced,
        modules: [
            { id: 'm7-1', title: 'Qualitative vs. Quantitative Analysis', type: 'text', content: 'Learn to assess both the numbers and the story behind a company.', durationMinutes: 30 },
            { id: 'm7-2', title: 'Valuation Models (DCF)', type: 'video', content: 'https://archive.org/download/BigBuckBunny_328/BigBuckBunny_512kb.mp4', durationMinutes: 60 },
        ],
        quizId: 'q7',
    },
    {
        id: 'course-8',
        title: 'Value Investing: The Buffett Way',
        description: 'Learn the timeless principles of value investing popularized by Warren Buffett. Find great companies at fair prices.',
        instructorId: 'user-3',
        thumbnailUrl: 'https://placehold.co/400x225/4f46e5/ffffff/png?font=lato&text=Value+Investing:+The+Buffett+Way',
        rating: 4.9,
        totalRatings: 450,
        price: 15999,
        category: 'Value Investing',
        difficulty: CourseDifficulty.Intermediate,
        modules: [
            { id: 'm8-1', title: 'Margin of Safety', type: 'text', content: 'Understand the most important concept in value investing.', durationMinutes: 20 },
            { id: 'm8-2', title: 'Economic Moats', type: 'video', content: 'https://archive.org/download/BigBuckBunny_328/BigBuckBunny_512kb.mp4', durationMinutes: 30 },
        ],
        quizId: 'q8',
    },
    {
        id: 'course-9',
        title: 'Growth Stock Investing Strategies',
        description: 'Discover how to identify and invest in innovative companies with the potential for explosive growth.',
        instructorId: 'user-5',
        thumbnailUrl: 'https://placehold.co/400x225/4f46e5/ffffff/png?font=lato&text=Growth+Stock+Investing+Strategies',
        rating: 4.7,
        totalRatings: 320,
        price: 15999,
        category: 'Growth Investing',
        difficulty: CourseDifficulty.Intermediate,
        modules: [
            { id: 'm9-1', title: 'Identifying High-Growth Sectors', type: 'text', content: 'Learn where to look for the next big thing.', durationMinutes: 25 },
            { id: 'm9-2', title: 'Evaluating Growth Metrics', type: 'text', content: 'Look at revenue growth, earnings growth, and market expansion.', durationMinutes: 35 },
        ],
        quizId: 'q9',
    },
    {
        id: 'course-10',
        title: 'Dividend Investing for Passive Income',
        description: 'Build a reliable stream of passive income by investing in stable companies that pay regular dividends.',
        instructorId: 'user-3',
        thumbnailUrl: 'https://placehold.co/400x225/4f46e5/ffffff/png?font=lato&text=Dividend+Investing+for+Passive+Income',
        rating: 4.8,
        totalRatings: 410,
        price: 10399,
        category: 'Income Investing',
        difficulty: CourseDifficulty.Beginner,
        modules: [
            { id: 'm10-1', title: 'Understanding Dividend Yield', type: 'text', content: 'Learn how to calculate and interpret dividend yield.', durationMinutes: 20 },
            { id: 'm10-2', title: 'Dividend Aristocrats', type: 'video', content: 'https://archive.org/download/BigBuckBunny_328/BigBuckBunny_512kb.mp4', durationMinutes: 25 },
        ],
        quizId: 'q10',
    },
    {
        id: 'course-11',
        title: 'Swing Trading Masterclass',
        description: 'Learn to profit from short-to-medium term market swings. This course covers strategies, stock selection, and risk management.',
        instructorId: 'user-5',
        thumbnailUrl: 'https://placehold.co/400x225/4f46e5/ffffff/png?font=lato&text=Swing+Trading+Masterclass',
        rating: 4.5,
        totalRatings: 180,
        price: 19999,
        category: 'Day & Swing Trading',
        difficulty: CourseDifficulty.Intermediate,
        modules: [
            { id: 'm11-1', title: 'Swing Trading Setups', type: 'video', content: 'https://archive.org/download/BigBuckBunny_328/BigBuckBunny_512kb.mp4', durationMinutes: 40 },
            { id: 'm11-2', title: 'Managing Swing Trades', type: 'text', content: 'Learn about entry, exit, and stop-loss strategies.', durationMinutes: 30 },
        ],
        quizId: 'q11',
    },
    {
        id: 'course-12',
        title: 'Day Trading for a Living',
        description: 'An intensive course on the strategies and discipline required for day trading. Not for the faint of heart.',
        instructorId: 'user-5',
        thumbnailUrl: 'https://placehold.co/400x225/4f46e5/ffffff/png?font=lato&text=Day+Trading+for+a+Living',
        rating: 4.3,
        totalRatings: 150,
        price: 31999,
        category: 'Day & Swing Trading',
        difficulty: CourseDifficulty.Advanced,
        modules: [
            { id: 'm12-1', title: 'Level 2 and Time & Sales', type: 'video', content: 'https://archive.org/download/BigBuckBunny_328/BigBuckBunny_512kb.mp4', durationMinutes: 50 },
            { id: 'm12-2', title: 'The Trader\'s Mindset', type: 'text', content: 'Learn the psychology needed to succeed in day trading.', durationMinutes: 30 },
        ],
        quizId: 'q12',
    },
    {
        id: 'course-13',
        title: 'Risk Management in Trading',
        description: 'The most important course you\'ll ever take. Learn how to protect your capital with position sizing, stop-losses, and portfolio diversification.',
        instructorId: 'user-3',
        thumbnailUrl: 'https://placehold.co/400x225/4f46e5/ffffff/png?font=lato&text=Risk+Management+in+Trading',
        rating: 4.9,
        totalRatings: 500,
        price: 11999,
        category: 'Risk Management',
        difficulty: CourseDifficulty.Beginner,
        modules: [
            { id: 'm13-1', title: 'The 1% Rule', type: 'text', content: 'A simple rule to protect your trading account from significant losses.', durationMinutes: 15 },
            { id: 'm13-2', title: 'Position Sizing', type: 'video', content: 'https://archive.org/download/BigBuckBunny_328/BigBuckBunny_512kb.mp4', durationMinutes: 25 },
        ],
        quizId: 'q13',
    },
    {
        id: 'course-14',
        title: 'The Psychology of Trading',
        description: 'Conquer fear and greed, the two biggest enemies of a trader. Master your emotions to make rational, profitable decisions.',
        instructorId: 'user-3',
        thumbnailUrl: 'https://placehold.co/400x225/4f46e5/ffffff/png?font=lato&text=The+Psychology+of+Trading',
        rating: 4.8,
        totalRatings: 380,
        price: 10399,
        category: 'Market Psychology',
        difficulty: CourseDifficulty.Intermediate,
        modules: [
            { id: 'm14-1', title: 'Understanding FOMO', type: 'text', content: 'Learn to deal with the "Fear Of Missing Out".', durationMinutes: 20 },
            { id: 'm14-2', title: 'Developing a Trading Plan', type: 'text', content: 'Your roadmap to disciplined trading.', durationMinutes: 30 },
        ],
        quizId: 'q14',
    },
    {
        id: 'course-15',
        title: 'Investing in IPOs',
        description: 'Learn how to evaluate and invest in Initial Public Offerings (IPOs). Understand the risks and rewards of buying into new companies.',
        instructorId: 'user-5',
        thumbnailUrl: 'https://placehold.co/400x225/4f46e5/ffffff/png?font=lato&text=Investing+in+IPOs',
        rating: 4.2,
        totalRatings: 95,
        price: 7999,
        category: 'Specialized Markets',
        difficulty: CourseDifficulty.Intermediate,
        modules: [
            { id: 'm15-1', title: 'Reading an S-1 Filing', type: 'text', content: 'How to analyze the official prospectus of a company going public.', durationMinutes: 30 },
            { id: 'm15-2', title: 'IPO Lock-up Periods', type: 'text', content: 'Understand why stock prices can be volatile after an IPO.', durationMinutes: 20 },
        ],
        quizId: 'q15',
    },
    {
        id: 'course-16',
        title: 'Real Estate Investment Trusts (REITs)',
        description: 'Invest in real estate without buying property. Learn how REITs work and how to add them to your portfolio for income and diversification.',
        instructorId: 'user-3',
        thumbnailUrl: 'https://placehold.co/400x225/4f46e5/ffffff/png?font=lato&text=Real+Estate+Investment+Trusts+(REITs)',
        rating: 4.6,
        totalRatings: 180,
        price: 7199,
        category: 'Specialized Markets',
        difficulty: CourseDifficulty.Beginner,
        modules: [
            { id: 'm16-1', title: 'Types of REITs', type: 'text', content: 'Explore equity, mortgage, and hybrid REITs.', durationMinutes: 25 },
            { id: 'm16-2', title: 'Analyzing a REIT', type: 'video', content: 'https://archive.org/download/BigBuckBunny_328/BigBuckBunny_512kb.mp4', durationMinutes: 30 },
        ],
        quizId: 'q16',
    },
    {
        id: 'course-17',
        title: 'Forex Trading for Beginners',
        description: 'Enter the world\'s largest financial market. Learn the basics of currency pairs, pips, leverage, and simple Forex trading strategies.',
        instructorId: 'user-5',
        thumbnailUrl: 'https://placehold.co/400x225/4f46e5/ffffff/png?font=lato&text=Forex+Trading+for+Beginners',
        rating: 4.4,
        totalRatings: 250,
        price: 11999,
        category: 'Specialized Markets',
        difficulty: CourseDifficulty.Beginner,
        modules: [
            { id: 'm17-1', title: 'Major Currency Pairs', type: 'text', content: 'Learn about pairs like EUR/USD, GBP/USD, and USD/JPY.', durationMinutes: 20 },
            { id: 'm17-2', title: 'Understanding Leverage', type: 'text', content: 'A double-edged sword in Forex trading.', durationMinutes: 25 },
        ],
        quizId: 'q17',
    },
    {
        id: 'course-18',
        title: 'Cryptocurrency Investing 101',
        description: 'A beginner-friendly guide to Bitcoin, Ethereum, and altcoins. Learn about blockchain, wallets, exchanges, and how to invest safely.',
        instructorId: 'user-5',
        thumbnailUrl: 'https://placehold.co/400x225/4f46e5/ffffff/png?font=lato&text=Cryptocurrency+Investing+101',
        rating: 4.7,
        totalRatings: 600,
        price: 15999,
        category: 'Specialized Markets',
        difficulty: CourseDifficulty.Beginner,
        modules: [
            { id: 'm18-1', title: 'What is Blockchain?', type: 'video', content: 'https://archive.org/download/BigBuckBunny_328/BigBuckBunny_512kb.mp4', durationMinutes: 30 },
            { id: 'm18-2', title: 'Setting up a Crypto Wallet', type: 'text', content: 'A step-by-step guide to securing your digital assets.', durationMinutes: 25 },
        ],
        quizId: 'q18',
    },
    {
        id: 'course-19',
        title: 'Building a Diversified Portfolio',
        description: 'Learn the principles of modern portfolio theory. Create a balanced, diversified portfolio to maximize returns for a given level of risk.',
        instructorId: 'user-3',
        thumbnailUrl: 'https://placehold.co/400x225/4f46e5/ffffff/png?font=lato&text=Building+a+Diversified+Portfolio',
        rating: 4.9,
        totalRatings: 300,
        price: 10399,
        category: 'Portfolio Management',
        difficulty: CourseDifficulty.Beginner,
        modules: [
            { id: 'm19-1', title: 'Asset Allocation', type: 'text', content: 'The most important decision an investor makes.', durationMinutes: 25 },
            { id: 'm19-2', title: 'Rebalancing Your Portfolio', type: 'text', content: 'How and when to adjust your holdings.', durationMinutes: 20 },
        ],
        quizId: 'q19',
    },
    {
        id: 'course-20',
        title: 'Retirement Investing (401k & IRA)',
        description: 'Plan for your future. This course covers the essentials of 401(k)s, Roth IRAs, Traditional IRAs, and how to invest for a comfortable retirement.',
        instructorId: 'user-3',
        thumbnailUrl: 'https://placehold.co/400x225/4f46e5/ffffff/png?font=lato&text=Retirement+Investing+(401k+&+IRA)',
        rating: 4.8,
        totalRatings: 420,
        price: 7999,
        category: 'Retirement Planning',
        difficulty: CourseDifficulty.Beginner,
        modules: [
            { id: 'm20-1', title: 'Roth vs. Traditional IRA', type: 'video', content: 'https://archive.org/download/BigBuckBunny_328/BigBuckBunny_512kb.mp4', durationMinutes: 20 },
            { id: 'm20-2', title: 'Understanding 401(k) Matching', type: 'text', content: 'Don\'t leave free money on the table!', durationMinutes: 15 },
        ],
        quizId: 'q20',
    },
    {
        id: 'course-21',
        title: 'Economic Indicators for Traders',
        description: 'Learn how to interpret key economic data like GDP, CPI, and employment reports to make informed trading decisions.',
        instructorId: 'user-5',
        thumbnailUrl: 'https://placehold.co/400x225/4f46e5/ffffff/png?font=lato&text=Economic+Indicators+for+Traders',
        rating: 4.5,
        totalRatings: 110,
        price: 14399,
        category: 'Economic Analysis',
        difficulty: CourseDifficulty.Intermediate,
        modules: [
            { id: 'm21-1', title: 'Gross Domestic Product (GDP)', type: 'text', content: 'The ultimate measure of an economy\'s health.', durationMinutes: 20 },
            { id: 'm21-2', title: 'The Consumer Price Index (CPI)', type: 'text', content: 'Understanding inflation and its impact on the market.', durationMinutes: 20 },
        ],
        quizId: 'q21',
    },
    {
        id: 'course-22',
        title: 'Sector Analysis and Rotation',
        description: 'Understand how different sectors of the economy perform during various stages of the business cycle and how to rotate your investments accordingly.',
        instructorId: 'user-5',
        thumbnailUrl: 'https://placehold.co/400x225/4f46e5/ffffff/png?font=lato&text=Sector+Analysis+and+Rotation',
        rating: 4.6,
        totalRatings: 90,
        price: 17599,
        category: 'Advanced Strategies',
        difficulty: CourseDifficulty.Intermediate,
        modules: [
            { id: 'm22-1', title: 'The 11 GICS Sectors', type: 'text', content: 'An overview of the major market sectors.', durationMinutes: 25 },
            { id: 'm22-2', title: 'Defensive vs. Cyclical Sectors', type: 'video', content: 'https://archive.org/download/BigBuckBunny_328/BigBuckBunny_512kb.mp4', durationMinutes: 30 },
        ],
        quizId: 'q22',
    },
    {
        id: 'course-23',
        title: 'Blue-Chip Stock Investing',
        description: 'A guide to investing in large, stable, and well-known companies. Learn how to select blue-chip stocks for long-term portfolio stability.',
        instructorId: 'user-3',
        thumbnailUrl: 'https://placehold.co/400x225/4f46e5/ffffff/png?font=lato&text=Blue-Chip+Stock+Investing',
        rating: 4.7,
        totalRatings: 310,
        price: 0,
        category: 'Investment Basics',
        difficulty: CourseDifficulty.Beginner,
        modules: [
            { id: 'm23-1', title: 'What Makes a Stock "Blue-Chip"?', type: 'text', content: 'Learn the characteristics of these market leaders.', durationMinutes: 15 },
            { id: 'm23-2', title: 'Building a Core Portfolio', type: 'text', content: 'Using blue-chip stocks as the foundation of your investments.', durationMinutes: 20 },
        ],
        quizId: 'q23',
    },
    {
        id: 'course-24',
        title: 'Mastering Candlestick Charts',
        description: 'An in-depth guide to reading and interpreting Japanese candlestick charts. Learn dozens of patterns to improve your trading accuracy.',
        instructorId: 'user-5',
        thumbnailUrl: 'https://placehold.co/400x225/4f46e5/ffffff/png?font=lato&text=Mastering+Candlestick+Charts',
        rating: 4.8,
        totalRatings: 290,
        price: 12799,
        category: 'Technical Analysis',
        difficulty: CourseDifficulty.Intermediate,
        modules: [
            { id: 'm24-1', title: 'Anatomy of a Candlestick', type: 'video', content: 'https://archive.org/download/BigBuckBunny_328/BigBuckBunny_512kb.mp4', durationMinutes: 20 },
            { id: 'm24-2', title: 'Bullish & Bearish Engulfing Patterns', type: 'text', content: 'A powerful reversal signal.', durationMinutes: 25 },
        ],
        quizId: 'q24',
    },
    {
        id: 'course-25',
        title: 'Fibonacci and Elliott Wave Theory',
        description: 'Explore two advanced technical analysis theories used to identify market cycles and predict price targets.',
        instructorId: 'user-5',
        thumbnailUrl: 'https://placehold.co/400x225/4f46e5/ffffff/png?font=lato&text=Fibonacci+and+Elliott+Wave+Theory',
        rating: 4.1,
        totalRatings: 75,
        price: 23999,
        category: 'Technical Analysis',
        difficulty: CourseDifficulty.Advanced,
        modules: [
            { id: 'm25-1', title: 'Fibonacci Retracements', type: 'text', content: 'Finding potential support and resistance levels.', durationMinutes: 30 },
            { id: 'm25-2', title: 'The Basic 5-3 Elliott Wave Pattern', type: 'video', content: 'https://archive.org/download/BigBuckBunny_328/BigBuckBunny_512kb.mp4', durationMinutes: 45 },
        ],
        quizId: 'q25',
    },
    {
        id: 'course-26',
        title: 'Bonds and Fixed-Income Securities',
        description: 'Diversify beyond stocks. Learn about government and corporate bonds, yield, duration, and the role of fixed income in a portfolio.',
        instructorId: 'user-3',
        thumbnailUrl: 'https://placehold.co/400x225/4f46e5/ffffff/png?font=lato&text=Bonds+and+Fixed-Income+Securities',
        rating: 4.6,
        totalRatings: 125,
        price: 7999,
        category: 'Portfolio Management',
        difficulty: CourseDifficulty.Beginner,
        modules: [
            { id: 'm26-1', title: 'How Bonds Work', type: 'text', content: 'Understanding coupon, maturity, and par value.', durationMinutes: 20 },
            { id: 'm26-2', title: 'Interest Rates and Bond Prices', type: 'text', content: 'Learn about their inverse relationship.', durationMinutes: 25 },
        ],
        quizId: 'q26',
    },
    {
        id: 'course-27',
        title: 'Socially Responsible Investing (ESG)',
        description: 'Align your investments with your values. Learn about Environmental, Social, and Governance (ESG) criteria and how to build a sustainable portfolio.',
        instructorId: 'user-3',
        thumbnailUrl: 'https://placehold.co/400x225/4f46e5/ffffff/png?font=lato&text=Socially+Responsible+Investing+(ESG)',
        rating: 4.7,
        totalRatings: 190,
        price: 6399,
        category: 'Investment Basics',
        difficulty: CourseDifficulty.Beginner,
        modules: [
            { id: 'm27-1', title: 'The Three Pillars of ESG', type: 'text', content: 'Breaking down Environmental, Social, and Governance factors.', durationMinutes: 25 },
            { id: 'm27-2', title: 'Finding ESG Funds', type: 'video', content: 'https://archive.org/download/BigBuckBunny_328/BigBuckBunny_512kb.mp4', durationMinutes: 20 },
        ],
        quizId: 'q27',
    },
    {
        id: 'course-28',
        title: 'Behavioral Finance',
        description: 'Understand the psychological biases that affect investors and learn how to avoid common mental errors to improve your returns.',
        instructorId: 'user-3',
        thumbnailUrl: 'https://placehold.co/400x225/4f46e5/ffffff/png?font=lato&text=Behavioral+Finance',
        rating: 4.9,
        totalRatings: 220,
        price: 11999,
        category: 'Market Psychology',
        difficulty: CourseDifficulty.Intermediate,
        modules: [
            { id: 'm28-1', title: 'Confirmation Bias', type: 'text', content: 'The tendency to favor information that confirms existing beliefs.', durationMinutes: 20 },
            { id: 'm28-2', title: 'Loss Aversion', type: 'text', content: 'Why losing $100 feels worse than gaining $100 feels good.', durationMinutes: 20 },
        ],
        quizId: 'q28',
    },
    {
        id: 'course-29',
        title: 'Technical Indicators Explained (MACD, RSI)',
        description: 'A practical guide to using popular technical indicators like Moving Averages, RSI, MACD, and Bollinger Bands to analyze charts.',
        instructorId: 'user-5',
        thumbnailUrl: 'https://placehold.co/400x225/4f46e5/ffffff/png?font=lato&text=Technical+Indicators+Explained+(MACD,+RSI)',
        rating: 4.6,
        totalRatings: 330,
        price: 11199,
        category: 'Technical Analysis',
        difficulty: CourseDifficulty.Intermediate,
        modules: [
            { id: 'm29-1', title: 'Moving Averages', type: 'video', content: 'https://archive.org/download/BigBuckBunny_328/BigBuckBunny_512kb.mp4', durationMinutes: 25 },
            { id: 'm29-2', title: 'Relative Strength Index (RSI)', type: 'text', content: 'Identifying overbought and oversold conditions.', durationMinutes: 30 },
        ],
        quizId: 'q29',
    },
    {
        id: 'course-30',
        title: 'Tax-Efficient Investing',
        description: 'It\'s not what you make, it\'s what you keep. Learn strategies to minimize taxes on your investment gains and dividends.',
        instructorId: 'user-3',
        thumbnailUrl: 'https://placehold.co/400x225/4f46e5/ffffff/png?font=lato&text=Tax-Efficient+Investing',
        rating: 4.7,
        totalRatings: 140,
        price: 9599,
        category: 'Retirement Planning',
        difficulty: CourseDifficulty.Intermediate,
        modules: [
            { id: 'm30-1', title: 'Tax-Advantaged Accounts', type: 'text', content: 'Utilizing 401(k)s, IRAs, and HSAs.', durationMinutes: 25 },
            { id: 'm30-2', title: 'Tax-Loss Harvesting', type: 'text', content: 'A strategy to offset capital gains with losses.', durationMinutes: 20 },
        ],
        quizId: 'q30',
    },
    {
        id: 'course-31',
        title: 'Options Greeks Explained (Delta, Gamma, Theta)',
        description: 'A deep dive into the forces that affect an option\'s price. Understanding the Greeks is essential for serious options traders.',
        instructorId: 'user-5',
        thumbnailUrl: 'https://placehold.co/400x225/4f46e5/ffffff/png?font=lato&text=Options+Greeks+Explained',
        rating: 4.6,
        totalRatings: 115,
        price: 22399,
        category: 'Advanced Strategies',
        difficulty: CourseDifficulty.Advanced,
        modules: [
            { id: 'm31-1', title: 'Delta: The Speed of an Option', type: 'text', content: 'How much an option\'s price changes for a $1 move in the stock.', durationMinutes: 25 },
            { id: 'm31-2', title: 'Theta: The Time Decay Factor', type: 'video', content: 'https://archive.org/download/BigBuckBunny_328/BigBuckBunny_512kb.mp4', durationMinutes: 30 },
        ],
        quizId: 'q31',
    },
    {
        id: 'course-32',
        title: 'Short Selling Techniques',
        description: 'Learn how to profit from a falling market. This course covers the mechanics, risks, and strategies of short selling.',
        instructorId: 'user-5',
        thumbnailUrl: 'https://placehold.co/400x225/4f46e5/ffffff/png?font=lato&text=Short+Selling+Techniques',
        rating: 4.0,
        totalRatings: 80,
        price: 15199,
        category: 'Advanced Strategies',
        difficulty: CourseDifficulty.Advanced,
        modules: [
            { id: 'm32-1', title: 'The Mechanics of Shorting', type: 'text', content: 'Borrowing shares to sell high and buy back low.', durationMinutes: 20 },
            { id: 'm32-2', title: 'The Risk of a Short Squeeze', type: 'text', content: 'Understanding the unlimited risk potential.', durationMinutes: 25 },
        ],
        quizId: 'q32',
    },
    {
        id: 'course-33',
        title: 'Financial Planning for Millennials',
        description: 'A complete guide for Gen Y. Covers budgeting, student loan management, investing basics, and planning for major life goals.',
        instructorId: 'user-3',
        thumbnailUrl: 'https://placehold.co/400x225/4f46e5/ffffff/png?font=lato&text=Financial+Planning+for+Millennials',
        rating: 4.8,
        totalRatings: 390,
        price: 3999,
        category: 'Retirement Planning',
        difficulty: CourseDifficulty.Beginner,
        modules: [
            { id: 'm33-1', title: 'The 50/30/20 Budget Rule', type: 'text', content: 'A simple framework for managing your money.', durationMinutes: 15 },
            { id: 'm33-2', title: 'Investing in Your 20s and 30s', type: 'video', content: 'https://archive.org/download/BigBuckBunny_328/BigBuckBunny_512kb.mp4', durationMinutes: 25 },
        ],
        quizId: 'q33',
    },
    {
        id: 'course-34',
        title: 'How to Analyze Tech Stocks',
        description: 'Learn the key metrics and qualitative factors for evaluating technology companies, from SaaS giants to semiconductor firms.',
        instructorId: 'user-5',
        thumbnailUrl: 'https://placehold.co/400x225/4f46e5/ffffff/png?font=lato&text=How+to+Analyze+Tech+Stocks',
        rating: 4.7,
        totalRatings: 260,
        price: 14399,
        category: 'Financial Analysis',
        difficulty: CourseDifficulty.Intermediate,
        modules: [
            { id: 'm34-1', title: 'Metrics for SaaS Companies', type: 'text', content: 'Understanding ARR, Churn, and LTV/CAC.', durationMinutes: 30 },
            { id: 'm34-2', title: 'Analyzing Network Effects', type: 'text', content: 'A powerful competitive advantage for tech companies.', durationMinutes: 20 },
        ],
        quizId: 'q34',
    },
    {
        id: 'course-35',
        title: 'Algorithmic Trading with Python',
        description: 'An advanced course for those with programming skills. Learn to backtest and deploy your own automated trading strategies using Python.',
        instructorId: 'user-5',
        thumbnailUrl: 'https://placehold.co/400x225/4f46e5/ffffff/png?font=lato&text=Algorithmic+Trading+with+Python',
        rating: 4.6,
        totalRatings: 130,
        price: 39999,
        category: 'Quantitative Trading',
        difficulty: CourseDifficulty.Advanced,
        modules: [
            { id: 'm35-1', title: 'Setting up Your Environment', type: 'text', content: 'Using libraries like Pandas, NumPy, and brokerage APIs.', durationMinutes: 45 },
            { id: 'm35-2', title: 'Backtesting a Simple Strategy', type: 'video', content: 'https://archive.org/download/BigBuckBunny_328/BigBuckBunny_512kb.mp4', durationMinutes: 75 },
        ],
        quizId: 'q35',
    },
    {
        id: 'course-36',
        title: 'Futures and Commodities Trading',
        description: 'Explore the world of futures contracts. Learn how to trade commodities like oil, gold, and agricultural products.',
        instructorId: 'user-5',
        thumbnailUrl: 'https://placehold.co/400x225/4f46e5/ffffff/png?font=lato&text=Futures+and+Commodities+Trading',
        rating: 4.2,
        totalRatings: 65,
        price: 20799,
        category: 'Specialized Markets',
        difficulty: CourseDifficulty.Advanced,
        modules: [
            { id: 'm36-1', title: 'Understanding Futures Contracts', type: 'text', content: 'Learn about contract specifications, margin, and expiration.', durationMinutes: 30 },
            { id: 'm36-2', title: 'Hedging with Futures', type: 'text', content: 'How producers and consumers use futures to manage price risk.', durationMinutes: 25 },
        ],
        quizId: 'q36',
    },
    {
        id: 'course-37',
        title: 'Building a Roth IRA Empire',
        description: 'Maximize your tax-free growth potential with a Roth IRA. This course covers contribution limits, investment strategies, and withdrawal rules.',
        instructorId: 'user-3',
        thumbnailUrl: 'https://placehold.co/400x225/4f46e5/ffffff/png?font=lato&text=Building+a+Roth+IRA+Empire',
        rating: 4.9,
        totalRatings: 480,
        price: 7999,
        category: 'Retirement Planning',
        difficulty: CourseDifficulty.Beginner,
        modules: [
            { id: 'm37-1', title: 'Roth IRA Contribution Rules', type: 'text', content: 'Learn about income limits and yearly maximums.', durationMinutes: 20 },
            { id: 'm37-2', title: 'Backdoor Roth IRA', type: 'text', content: 'A strategy for high-income earners.', durationMinutes: 25 },
        ],
        quizId: 'q37',
    },
    {
        id: 'course-38',
        title: 'Margin Trading and Leverage',
        description: 'Understand how to use borrowed money to amplify your returns (and risks). This course covers margin calls, interest, and when to use leverage.',
        instructorId: 'user-5',
        thumbnailUrl: 'https://placehold.co/400x225/4f46e5/ffffff/png?font=lato&text=Margin+Trading+and+Leverage',
        rating: 4.1,
        totalRatings: 95,
        price: 11999,
        category: 'Risk Management',
        difficulty: CourseDifficulty.Intermediate,
        modules: [
            { id: 'm38-1', title: 'How Margin Works', type: 'text', content: 'The basics of borrowing from your broker.', durationMinutes: 20 },
            { id: 'm38-2', title: 'What is a Margin Call?', type: 'video', content: 'https://archive.org/download/BigBuckBunny_328/BigBuckBunny_512kb.mp4', durationMinutes: 25 },
        ],
        quizId: 'q38',
    },
    {
        id: 'course-39',
        title: 'Small-Cap and Mid-Cap Gems',
        description: 'Learn how to analyze and find promising small and mid-sized companies before they become household names.',
        instructorId: 'user-5',
        thumbnailUrl: 'https://placehold.co/400x225/4f46e5/ffffff/png?font=lato&text=Small-Cap+and+Mid-Cap+Gems',
        rating: 4.6,
        totalRatings: 170,
        price: 18399,
        category: 'Growth Investing',
        difficulty: CourseDifficulty.Intermediate,
        modules: [
            { id: 'm39-1', title: 'The Risk and Reward of Small-Caps', type: 'text', content: 'Why smaller companies have higher growth potential.', durationMinutes: 25 },
            { id: 'm39-2', title: 'Finding Information on Small Companies', type: 'text', content: 'Where to look when analyst coverage is sparse.', durationMinutes: 30 },
        ],
        quizId: 'q39',
    },
    {
        id: 'course-40',
        title: 'Global and Emerging Markets',
        description: 'Diversify your portfolio internationally. Learn about the opportunities and risks of investing in developed and emerging economies.',
        instructorId: 'user-3',
        thumbnailUrl: 'https://placehold.co/400x225/4f46e5/ffffff/png?font=lato&text=Global+and+Emerging+Markets',
        rating: 4.4,
        totalRatings: 110,
        price: 11199,
        category: 'Specialized Markets',
        difficulty: CourseDifficulty.Intermediate,
        modules: [
            { id: 'm40-1', title: 'ADRs and Foreign Stock Investing', type: 'text', content: 'How to easily buy shares of international companies.', durationMinutes: 25 },
            { id: 'm40-2', title: 'Currency Risk', type: 'text', content: 'An extra layer of risk to consider when investing abroad.', durationMinutes: 20 },
        ],
        quizId: 'q40',
    },
    {
        id: 'course-41',
        title: 'Financial Modeling and Valuation',
        description: 'A hands-on course teaching you how to build financial models in Excel from scratch to value a company.',
        instructorId: 'user-3',
        thumbnailUrl: 'https://placehold.co/400x225/4f46e5/ffffff/png?font=lato&text=Financial+Modeling+and+Valuation',
        rating: 4.7,
        totalRatings: 160,
        price: 27999,
        category: 'Financial Analysis',
        difficulty: CourseDifficulty.Advanced,
        modules: [
            { id: 'm41-1', title: 'Building a 3-Statement Model', type: 'video', content: 'https://archive.org/download/BigBuckBunny_328/BigBuckBunny_512kb.mp4', durationMinutes: 60 },
            { id: 'm41-2', title: 'Discounted Cash Flow (DCF) Analysis', type: 'video', content: 'https://archive.org/download/BigBuckBunny_328/BigBuckBunny_512kb.mp4', durationMinutes: 75 },
        ],
        quizId: 'q41',
    },
    {
        id: 'course-42',
        title: 'Hedge Fund Strategies',
        description: 'An overview of common strategies used by hedge funds, such as long/short equity, global macro, and event-driven investing.',
        instructorId: 'user-5',
        thumbnailUrl: 'https://placehold.co/400x225/4f46e5/ffffff/png?font=lato&text=Hedge+Fund+Strategies',
        rating: 4.3,
        totalRatings: 90,
        price: 23999,
        category: 'Advanced Strategies',
        difficulty: CourseDifficulty.Advanced,
        modules: [
            { id: 'm42-1', title: 'Long/Short Equity', type: 'text', content: 'The classic hedge fund strategy of being long good stocks and short bad ones.', durationMinutes: 30 },
            { id: 'm42-2', title: 'Merger Arbitrage', type: 'text', content: 'Profiting from the price discrepancy of announced mergers.', durationMinutes: 25 },
        ],
        quizId: 'q42',
    },
    {
        id: 'course-43',
        title: 'Peter Lynch\'s "One Up On Wall Street"',
        description: 'A course based on the legendary investor Peter Lynch\'s philosophy. Learn how to use your local knowledge to find "tenbaggers".',
        instructorId: 'user-3',
        thumbnailUrl: 'https://placehold.co/400x225/4f46e5/ffffff/png?font=lato&text=Peter+Lynch\'s+"One+Up+On+Wall+Street"',
        rating: 4.9,
        totalRatings: 400,
        price: 11999,
        category: 'Value Investing',
        difficulty: CourseDifficulty.Intermediate,
        modules: [
            { id: 'm43-1', title: 'Invest in What You Know', type: 'text', content: 'The core principle of Lynch\'s strategy.', durationMinutes: 20 },
            { id: 'm43-2', title: 'Six Categories of Stocks', type: 'video', content: 'https://archive.org/download/BigBuckBunny_328/BigBuckBunny_512kb.mp4', durationMinutes: 30 },
        ],
        quizId: 'q43',
    },
    {
        id: 'course-44',
        title: 'Investing in the Healthcare Sector',
        description: 'An analysis of the healthcare industry, from large pharmaceuticals and biotech to medical device companies and insurers.',
        instructorId: 'user-3',
        thumbnailUrl: 'https://placehold.co/400x225/4f46e5/ffffff/png?font=lato&text=Investing+in+the+Healthcare+Sector',
        rating: 4.5,
        totalRatings: 135,
        price: 13599,
        category: 'Financial Analysis',
        difficulty: CourseDifficulty.Intermediate,
        modules: [
            { id: 'm44-1', title: 'Understanding Clinical Trials', type: 'text', content: 'The key driver for biotech stock prices.', durationMinutes: 30 },
            { id: 'm44-2', title: 'Patent Cliffs', type: 'text', content: 'A major risk for pharmaceutical companies.', durationMinutes: 20 },
        ],
        quizId: 'q44',
    },
    {
        id: 'course-45',
        title: 'Penny Stocks: Risks and Opportunities',
        description: 'A realistic look at the world of penny stocks. This course focuses heavily on risk management and how to spot potential scams.',
        instructorId: 'user-5',
        thumbnailUrl: 'https://placehold.co/400x225/4f46e5/ffffff/png?font=lato&text=Penny+Stocks:+Risks+and+Opportunities',
        rating: 3.8,
        totalRatings: 150,
        price: 7999,
        category: 'Risk Management',
        difficulty: CourseDifficulty.Beginner,
        modules: [
            { id: 'm45-1', title: 'What Defines a Penny Stock?', type: 'text', content: 'Understanding the low price and market capitalization.', durationMinutes: 15 },
            { id: 'm45-2', title: 'Avoiding "Pump and Dump" Schemes', type: 'video', content: 'https://archive.org/download/BigBuckBunny_328/BigBuckBunny_512kb.mp4', durationMinutes: 25 },
        ],
        quizId: 'q45',
    },
    {
        id: 'course-46',
        title: 'Advanced Technical Analysis',
        description: 'Go beyond basic indicators. This course covers Ichimoku Clouds, Volume Profile, and Market Profile for a deeper view of the market.',
        instructorId: 'user-5',
        thumbnailUrl: 'https://placehold.co/400x225/4f46e5/ffffff/png?font=lato&text=Advanced+Technical+Analysis',
        rating: 4.4,
        totalRatings: 95,
        price: 26399,
        category: 'Technical Analysis',
        difficulty: CourseDifficulty.Advanced,
        modules: [
            { id: 'm46-1', title: 'The Ichimoku Cloud', type: 'video', content: 'https://archive.org/download/BigBuckBunny_328/BigBuckBunny_512kb.mp4', durationMinutes: 45 },
            { id: 'm46-2', title: 'Volume Profile Basics', type: 'text', content: 'Understanding price levels with high and low trading volume.', durationMinutes: 35 },
        ],
        quizId: 'q46',
    },
    {
        id: 'course-47',
        title: 'Long-Term Investment Strategies',
        description: 'A course focused on building wealth over decades, not days. Learn about buy-and-hold, dollar-cost averaging, and the power of compounding.',
        instructorId: 'user-3',
        thumbnailUrl: 'https://placehold.co/400x225/4f46e5/ffffff/png?font=lato&text=Long-Term+Investment+Strategies',
        rating: 4.9,
        totalRatings: 550,
        price: 0,
        category: 'Investment Basics',
        difficulty: CourseDifficulty.Beginner,
        modules: [
            { id: 'm47-1', title: 'The Power of Compounding', type: 'video', content: 'https://archive.org/download/BigBuckBunny_328/BigBuckBunny_512kb.mp4', durationMinutes: 20 },
            { id: 'm47-2', title: 'Dollar-Cost Averaging Explained', type: 'text', content: 'A simple strategy to reduce risk and invest consistently.', durationMinutes: 15 },
        ],
        quizId: 'q47',
    },
    {
        id: 'course-48',
        title: 'Options for Hedging Your Portfolio',
        description: 'Learn how to use options not for speculation, but as insurance. Protect your stock portfolio from market downturns using protective puts and collars.',
        instructorId: 'user-5',
        thumbnailUrl: 'https://placehold.co/400x225/4f46e5/ffffff/png?font=lato&text=Options+for+Hedging+Your+Portfolio',
        rating: 4.6,
        totalRatings: 105,
        price: 15999,
        category: 'Risk Management',
        difficulty: CourseDifficulty.Intermediate,
        modules: [
            { id: 'm48-1', title: 'Protective Puts', type: 'text', content: 'The simplest way to hedge a long stock position.', durationMinutes: 25 },
            { id: 'm48-2', title: 'The Collar Strategy', type: 'text', content: 'Financing a protective put by selling a covered call.', durationMinutes: 30 },
        ],
        quizId: 'q48',
    },
    {
        id: 'course-49',
        title: 'Trading with Exchange Traded Notes (ETNs)',
        description: 'Understand the structure and risks of ETNs. Learn how they differ from ETFs and when they might be used in a portfolio.',
        instructorId: 'user-3',
        thumbnailUrl: 'https://placehold.co/400x225/4f46e5/ffffff/png?font=lato&text=Trading+with+ETNs',
        rating: 4.0,
        totalRatings: 60,
        price: 7199,
        category: 'Specialized Markets',
        difficulty: CourseDifficulty.Intermediate,
        modules: [
            { id: 'm49-1', title: 'ETN vs. ETF', type: 'text', content: 'Key differences in structure and risk.', durationMinutes: 25 },
            { id: 'm49-2', title: 'Credit Risk in ETNs', type: 'text', content: 'Understanding that ETNs are unsecured debt notes.', durationMinutes: 20 },
        ],
        quizId: 'q49',
    },
    {
        id: 'course-50',
        title: 'Market Making and Liquidity',
        description: 'An advanced look at how market makers provide liquidity and profit from the bid-ask spread. Understand the plumbing of the financial markets.',
        instructorId: 'user-5',
        thumbnailUrl: 'https://placehold.co/400x225/4f46e5/ffffff/png?font=lato&text=Market+Making+and+Liquidity',
        rating: 4.3,
        totalRatings: 55,
        price: 27999,
        category: 'Advanced Strategies',
        difficulty: CourseDifficulty.Advanced,
        modules: [
            { id: 'm50-1', title: 'The Bid-Ask Spread', type: 'text', content: 'The fundamental source of profit for market makers.', durationMinutes: 20 },
            { id: 'm50-2', title: 'Payment for Order Flow', type: 'video', content: 'https://archive.org/download/BigBuckBunny_328/BigBuckBunny_512kb.mp4', durationMinutes: 30 },
        ],
        quizId: 'q50',
    }
];

// STUDENT PROGRESS
export const STUDENT_PROGRESS: StudentProgress[] = [
    { 
        courseId: 'course-1',
        studentId: 'user-1',
        completedModules: ['m1-1'],
        quizScore: null,
        assignmentStatus: 'pending',
        completionNotified: false,
        certificateIssued: false,
    }
];

// CHAT MESSAGES
export const CHAT_MESSAGES: ChatMessage[] = [
    { id: 'msg-1', user: USERS[2], timestamp: new Date(Date.now() - 60000 * 5), text: 'Welcome to the community chat!' },
    { id: 'msg-2', user: USERS[0], timestamp: new Date(Date.now() - 60000 * 4), text: 'Hi everyone! Glad to be here.' },
    { id: 'msg-3', user: USERS[1], timestamp: new Date(Date.now() - 60000 * 3), text: 'Looking forward to the advanced course.' },
];

// LIVE SESSIONS
const now = new Date();
const session1StartTime = new Date(now.getTime() + 86400000 * 2);
const session2StartTime = new Date(now.getTime() + 86400000 * 5);

export const LIVE_SESSIONS: LiveSession[] = [
    { id: 'ls-1', title: 'Weekly Market Analysis', description: 'Join us for a live breakdown of this week\'s market trends and what to look out for.', instructorId: 'user-3', dateTime: session1StartTime, endTime: new Date(session1StartTime.getTime() + 60 * 60 * 1000), price: 1599, attendeeIds: ['user-1'] },
    { id: 'ls-2', title: 'Q&A with a Pro Trader', description: 'Ask your most pressing trading questions to an experienced professional.', instructorId: 'user-5', dateTime: session2StartTime, endTime: new Date(session2StartTime.getTime() + 60 * 60 * 1000), price: 0, attendeeIds: [] }
];


// 1-on-1 SESSIONS
export const ONE_TO_ONE_SESSIONS: OneToOneSession[] = [
    { id: 'oto-1', studentId: 'user-1', instructorId: 'user-3', dateTime: new Date(Date.now() + 86400000 * 3), status: 'scheduled', requestedById: 'user-3' },
    { id: 'oto-2', studentId: 'user-2', instructorId: 'user-5', dateTime: new Date(Date.now() - 86400000 * 1), status: 'completed', requestedById: 'user-2' },
    { id: 'oto-3', studentId: 'user-1', instructorId: 'user-5', dateTime: new Date(Date.now() + 86400000 * 4), status: 'pending', requestedById: 'user-1' },
];

// BANNERS
export const BANNERS: Banner[] = [
    // Student Banners
    {
        id: 'banner-1',
        title: (name) => `Welcome back, ${name}!`,
        subtitle: 'Ready to continue your learning journey? Your personalized dashboard awaits.',
        ctaText: 'View My Courses',
        ctaLink: 'courses',
        background: 'bg-gradient-to-br from-indigo-600 to-violet-500',
        roles: [UserRole.Student],
    },
    {
        id: 'banner-2',
        title: () => `Flash Sale This Weekend!`,
        subtitle: 'Get up to 50% off on our most popular trading courses. Don\'t miss out on this limited-time offer.',
        ctaText: 'Explore Courses',
        ctaLink: 'courses',
        background: 'bg-gradient-to-br from-amber-500 to-orange-600',
        roles: [UserRole.Student],
    },
    {
        id: 'banner-3',
        title: () => `New Course: "Crypto Investing 101"`,
        subtitle: 'Dive into the world of digital assets. Learn about blockchain, wallets, and how to invest safely in cryptocurrencies.',
        ctaText: 'Enroll Now',
        ctaLink: 'course-18', // ID of the crypto course
        background: 'bg-gradient-to-br from-teal-500 to-cyan-600',
        roles: [UserRole.Student],
    },
    {
        id: 'banner-4',
        title: () => `Unlock Personalized Coaching`,
        subtitle: 'Book a 1-on-1 session with our expert instructors to get dedicated guidance and accelerate your learning curve.',
        ctaText: 'Book a Session',
        ctaLink: 'sessions',
        background: 'bg-gradient-to-br from-slate-800 to-slate-700',
        roles: [UserRole.Student],
    },
    // Instructor Banners
    {
        id: 'banner-inst-1',
        title: (name) => `Share your knowledge, ${name}!`,
        subtitle: 'Ready to create your next bestseller? Our course creation tools make it easy.',
        ctaText: 'Create a Course',
        ctaLink: 'courses',
        background: 'bg-gradient-to-br from-teal-600 to-sky-500',
        roles: [UserRole.Instructor],
    },
    {
        id: 'banner-inst-2',
        title: () => `Engage with Your Students`,
        subtitle: 'Check the community chat for new messages and respond to 1-on-1 session requests.',
        ctaText: 'View Community',
        ctaLink: 'community',
        background: 'bg-gradient-to-br from-rose-500 to-pink-500',
        roles: [UserRole.Instructor],
    },
    // Admin Banners
    {
        id: 'banner-admin-1',
        title: () => 'Platform Overview',
        subtitle: 'Get a birds-eye view of all platform activity, from user growth to course engagement.',
        ctaText: 'View Analytics',
        ctaLink: 'analytics',
        background: 'bg-gradient-to-br from-slate-800 to-slate-700',
        roles: [UserRole.Admin],
    },
    {
        id: 'banner-admin-2',
        title: () => 'Manage Your Platform',
        subtitle: 'Oversee users, manage course content, and ensure the community is thriving.',
        ctaText: 'Manage Users',
        ctaLink: 'users',
        background: 'bg-gradient-to-br from-red-600 to-orange-500',
        roles: [UserRole.Admin],
    }
];